### ISSUE TITLE
UNAUTHORIZED

### ISSUE THREAD

**Issue by xinlinsoft** [paypay/paypayopa-sdk-java#78]
running createqrcode prompts unauthorized， What's the problem
![image](https://user-images.githubusercontent.com/76423095/103866297-86e5f780-5100-11eb-8946-ee0bb6a72883.png)

**Comment by javidlulu** [comment]
It seems from our log you are setting setAssumeMerchant to ASSUME_MERCHANT_ID, request you to please set the correct merchant id and try

**Comment by shreyanshp** [comment]
@xinlinsoft Let us know if you have any more queries or issues, in the meantime I will close this issue
